[package]
name = "bench-redis-deadpool"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
deadpool-redis = { version = "0.18.0", features = ["tokio"] }
redis = { version = "0.27.6", features = ["tokio-comp"] }
